name: Daily Weather Forecast

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run forecast
        run: python forecast.py
